---
- name: Tab Five
  hosts: your_target_hosts
  gather_facts: yes
  become: yes

  tasks:
    - name: 5.6.4- Ensure default group for root account is GID 0
      group:
        name: root
        state: present
        gid: 0
    - name: 5.6.1.1 - Ensure password expiration date is 365 days or less
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS 365'

    - name: Get list of all users with passwords
      shell: cat /etc/shadow | grep -v ':\*:$' | cut -d ':' -f1
      register: users_with_passwords
      changed_when: false

    - name: Modify user parameters for all users with a password set to match 365
      shell: chage --maxdays 365 {{ item }}
      loop: "{{ users_with_passwords.stdout_lines }}"
      changed_when: false

    - name: 5.6.1.2 - Ensure minimum days between password changes is 7 or more
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MIN_DAYS'
        line: 'PASS_MIN_DAYS 7'

    - name: Modify user parameters for all users with a password set to match 7
      shell: chage --mindays 7 {{ item }}
      loop: "{{ users_with_passwords.stdout_lines }}"
      changed_when: false

    - name: 5.6.1.3- Ensure password expiration warning days is 7 or more
      lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_WARN_AGE'
        line: 'PASS_WARN_AGE 7'

    - name:  Modify user parameters for all users with a password set to matc    h 7   
      shell: chage --warndays 7 {{ item }}
      loop: "{{ users_with_passwords.stdout_lines }}"
      changed_when: false


  
      
